#spring:
#  datasource:
#    username: henry
#    password: henry
#    url: jdbc:mysql://localhost:3306/jeep?serverTimezone=UTC
#
# 
#logging:
#  level:
#    root: warn
#    '[com.promineotech]': debug